# Site settings
title: Partner Zonder Papieren  
header-img: img/home-bg.jpg
email: contact@partnerzonderpapieren.nl
description: "De verborgen wereld van interculturele liefde. interculturele relaties, illegale partner, vluchtelingen, gezinshereniging, verblijfsvergunning."
baseurl: ""
url: "http://partnerzonderpapieren.nl"
twitter_username: partnerpapieren
facebook_username:  partnerzonderpapieren

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
